import { type NextRequest, NextResponse } from "next/server"
import { successResponse, errorResponse, handleApiError } from "@/lib/api-response"
import { query } from "@/lib/database"
import { requireCadastroAccess, apiAuthError } from "@/lib/api-auth"

function failure(error: unknown) { const auth = apiAuthError(error); return { body: auth ? { success: false, message: auth.message } : handleApiError(error), status: auth?.status || 500 } }

export async function GET(_: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { administradoraId } = await requireCadastroAccess("view"); const { id } = await params; const rows = await query("SELECT e.*, e.status AS situacao, p.nome_completo, pj.nome_fantasia, pj.razao_social, pf.cpf AS pessoa_cpf, pj.cnpj AS pessoa_cnpj FROM estipulantes e JOIN pessoas p ON p.id = e.pessoa_id LEFT JOIN pessoas_fisicas pf ON pf.pessoa_id = p.id LEFT JOIN pessoas_juridicas pj ON pj.pessoa_id = p.id WHERE e.id = $1 AND e.administradora_id = $2 AND e.deleted_at IS NULL AND p.deleted_at IS NULL", [Number(id), administradoraId]); return rows[0] ? NextResponse.json(successResponse(rows[0])) : NextResponse.json(errorResponse("Estipulante não encontrado"), { status: 404 }) } catch (error) { const result = failure(error); return NextResponse.json(result.body, { status: result.status }) } }

export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { administradoraId } = await requireCadastroAccess("edit"); const { id } = await params; const body = await request.json(); const normalizedBody = { ...body, status: body.status ?? body.situacao }
    const allowed = ["codigo_estipulante", "operadora_id", "status"]; const entries = Object.entries(normalizedBody).filter(([key]) => allowed.includes(key)); if (!entries.length) return NextResponse.json(errorResponse("Nenhum campo válido para atualizar"), { status: 400 }); const values = entries.map(([, value]) => value); const updates = entries.map(([key], index) => `${key} = $${index + 1}`); values.push(Number(id), administradoraId); const rows = await query(`UPDATE estipulantes SET ${updates.join(", ")}, updated_at = CURRENT_TIMESTAMP WHERE id = $${values.length - 1} AND administradora_id = $${values.length} AND deleted_at IS NULL RETURNING *`, values); return rows[0] ? NextResponse.json(successResponse(rows[0], "Estipulante atualizado com sucesso")) : NextResponse.json(errorResponse("Estipulante não encontrado"), { status: 404 }) } catch (error) { const result = failure(error); return NextResponse.json(result.body, { status: result.status }) } }

export async function DELETE(_: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { administradoraId } = await requireCadastroAccess("delete"); const { id } = await params; const rows = await query("UPDATE estipulantes SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND administradora_id = $2 AND deleted_at IS NULL RETURNING id", [Number(id), administradoraId]); return rows[0] ? NextResponse.json(successResponse(null, "Estipulante excluído com sucesso")) : NextResponse.json(errorResponse("Estipulante não encontrado"), { status: 404 }) } catch (error) { const result = failure(error); return NextResponse.json(result.body, { status: result.status }) } }
