-- Faturamento mensal: configurações, templates, documentos, pagamentos e arquivos bancários.
-- Tabelas legadas de parcelas permanecem isoladas e não são removidas.

CREATE TABLE IF NOT EXISTS configuracoes_cobranca (id BIGSERIAL PRIMARY KEY, administradora_id BIGINT NOT NULL, nome VARCHAR(160) NOT NULL, banco_codigo VARCHAR(10), agencia VARCHAR(20), conta VARCHAR(30), carteira VARCHAR(30), convenio VARCHAR(50), ambiente VARCHAR(20) NOT NULL DEFAULT 'homologacao', ativo BOOLEAN NOT NULL DEFAULT true, preferencias JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS templates_arquivos_bancarios (id BIGSERIAL PRIMARY KEY, configuracao_id BIGINT NOT NULL REFERENCES configuracoes_cobranca(id), administradora_id BIGINT NOT NULL, tipo VARCHAR(20) NOT NULL, meio VARCHAR(30) NOT NULL, layout VARCHAR(30) NOT NULL, versao VARCHAR(30) NOT NULL DEFAULT '1.0', encoding VARCHAR(30) NOT NULL DEFAULT 'UTF-8', delimitador VARCHAR(5), template JSONB NOT NULL DEFAULT '{}'::jsonb, ativo BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT templates_arquivos_tipo_chk CHECK (tipo IN ('remessa','retorno')));
CREATE TABLE IF NOT EXISTS fatura_eventos (id BIGSERIAL PRIMARY KEY, fatura_id BIGINT NOT NULL, administradora_id BIGINT NOT NULL, tipo VARCHAR(40) NOT NULL, status_anterior VARCHAR(30), status_novo VARCHAR(30), origem VARCHAR(30) NOT NULL DEFAULT 'sistema', payload JSONB NOT NULL DEFAULT '{}'::jsonb, usuario_id BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS fatura_documentos (id BIGSERIAL PRIMARY KEY, fatura_id BIGINT NOT NULL, administradora_id BIGINT NOT NULL, meio VARCHAR(30) NOT NULL, versao INTEGER NOT NULL DEFAULT 1, identificador VARCHAR(120), conteudo TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(30) NOT NULL DEFAULT 'emitido', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE (administradora_id, fatura_id, meio, versao));
CREATE TABLE IF NOT EXISTS pagamentos_faturas (id BIGSERIAL PRIMARY KEY, fatura_id BIGINT NOT NULL, administradora_id BIGINT NOT NULL, meio VARCHAR(30) NOT NULL, idempotency_key VARCHAR(160) NOT NULL, valor NUMERIC(14,2) NOT NULL, data_pagamento DATE NOT NULL DEFAULT CURRENT_DATE, identificador_externo VARCHAR(160), status VARCHAR(30) NOT NULL DEFAULT 'confirmado', retorno_bruto JSONB NOT NULL DEFAULT '{}'::jsonb, usuario_id BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE (administradora_id, idempotency_key));
CREATE TABLE IF NOT EXISTS arquivos_bancarios (id BIGSERIAL PRIMARY KEY, administradora_id BIGINT NOT NULL, configuracao_id BIGINT, template_id BIGINT, tipo VARCHAR(20) NOT NULL, meio VARCHAR(30) NOT NULL, nome_arquivo VARCHAR(255) NOT NULL, conteudo TEXT, status VARCHAR(30) NOT NULL DEFAULT 'gerado', total_itens INTEGER NOT NULL DEFAULT 0, valor_total NUMERIC(14,2) NOT NULL DEFAULT 0, resumo JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), processed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS arquivo_bancario_itens (id BIGSERIAL PRIMARY KEY, arquivo_id BIGINT NOT NULL REFERENCES arquivos_bancarios(id), fatura_id BIGINT, administradora_id BIGINT NOT NULL, codigo_ocorrencia VARCHAR(30), valor NUMERIC(14,2), linha_original TEXT, status VARCHAR(30) NOT NULL DEFAULT 'pendente', mensagem TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
