import { type NextRequest, NextResponse } from "next/server"
import { successResponse, errorResponse, handleApiError } from "@/lib/api-response"
import { query } from "@/lib/database"
import { requireCadastroAccess, apiAuthError } from "@/lib/api-auth"

function failure(error: unknown) { const auth = apiAuthError(error); return { body: auth ? { success: false, message: auth.message } : handleApiError(error), status: auth?.status || 500 } }

export async function GET(_: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { administradoraId } = await requireCadastroAccess("view"); const { id } = await params; const rows = await query("SELECT * FROM agenciadores WHERE id = $1 AND administradora_id = $2 AND deleted_at IS NULL", [Number(id), administradoraId]); return rows[0] ? NextResponse.json(successResponse(rows[0])) : NextResponse.json({ success: false, message: "Agenciador não encontrado" }, { status: 404 }) } catch (error) { const result = failure(error); return NextResponse.json(result.body, { status: result.status }) } }

export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try { const { administradoraId } = await requireCadastroAccess("edit"); const { id } = await params; const body = await request.json(); const allowed = ["corretor_id", "comissao_percentual", "situacao"]; const entries = Object.entries(body).filter(([key]) => allowed.includes(key)); if (!entries.length) return NextResponse.json({ success: false, message: "Nenhum campo válido para atualizar" }, { status: 400 }); const values = entries.map(([, value]) => value); const updates = entries.map(([key], index) => `${key} = $${index + 1}`); values.push(Number(id), administradoraId); const rows = await query(`UPDATE agenciadores SET ${updates.join(", ")}, updated_at = CURRENT_TIMESTAMP WHERE id = $${values.length - 1} AND administradora_id = $${values.length} AND deleted_at IS NULL RETURNING *`, values); return rows[0] ? NextResponse.json(successResponse(rows[0], "Agenciador atualizado com sucesso")) : NextResponse.json({ success: false, message: "Agenciador não encontrado" }, { status: 404 }) } catch (error) { const result = failure(error); return NextResponse.json(result.body, { status: result.status }) }
}

export async function DELETE(_: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { administradoraId } = await requireCadastroAccess("delete"); const { id } = await params; const rows = await query("UPDATE agenciadores SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND administradora_id = $2 AND deleted_at IS NULL RETURNING id", [Number(id), administradoraId]); return rows[0] ? NextResponse.json(successResponse(null, "Agenciador excluído com sucesso")) : NextResponse.json({ success: false, message: "Agenciador não encontrado" }, { status: 404 }) } catch (error) { const result = failure(error); return NextResponse.json(result.body, { status: result.status }) } }
