"use client"

import { useEffect, useMemo, useState } from "react"
import { Database, Download, Play, RefreshCw, Search, ShieldCheck, Table2, Terminal, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Textarea } from "@/components/ui/textarea"
import { toast } from "sonner"

type TableInfo = { table_name: string; row_count: number }
type Result = { columns: string[]; rows: Record<string, unknown>[]; executionTime?: number; affectedRows?: number }

function download(text: string, name: string, type: string) { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([text], { type })); a.download = name; a.click(); URL.revokeObjectURL(a.href) }
function csv(result: Result) { return [result.columns.join(","), ...result.rows.map(row => result.columns.map(c => JSON.stringify(row[c] ?? "")).join(","))].join("\n") }

export default function SqlManagerPage() {
  const [tables, setTables] = useState<TableInfo[]>([]); const [filter, setFilter] = useState(""); const [selected, setSelected] = useState(""); const [detail, setDetail] = useState<Result | null>(null); const [sql, setSql] = useState("SELECT * FROM usuarios LIMIT 50"); const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(false)
  const loadTables = async () => { const r = await fetch("/api/sql-manager/tables"); const d = await r.json(); if (!r.ok) return toast.error(d.error); setTables(d.tables) }
  useEffect(() => { loadTables() }, [])
  const openTable = async (name: string) => { setSelected(name); setBusy(true); const r = await fetch(`/api/sql-manager/query?table=${encodeURIComponent(name)}`); const d = await r.json(); setBusy(false); if (!r.ok) return toast.error(d.error); setDetail({ columns: d.columns.map((c: any) => c.column_name), rows: d.rows }); setSql(`SELECT * FROM ${name} LIMIT 50`) }
  const execute = async () => { const kind = sql.trim().split(/\s+/)[0]?.toUpperCase(); const isWrite = ["INSERT", "UPDATE", "DELETE"].includes(kind); if (isWrite && !window.confirm(`Confirmar operação ${kind}? Esta ação altera dados do banco.`)) return; setBusy(true); const r = await fetch("/api/sql-manager/query", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sql, confirmWrite: isWrite }) }); const d = await r.json(); setBusy(false); if (!r.ok) return toast.error(d.error); setResult(d); toast.success(`${kind} executado com sucesso`); loadTables() }
  const active = result || detail; const visible = useMemo(() => tables.filter(t => t.table_name.toLowerCase().includes(filter.toLowerCase())), [tables, filter])
  return <div className="flex min-h-full flex-col gap-6">
    <header className="relative overflow-hidden rounded-3xl border border-border bg-primary p-6 text-primary-foreground shadow-xl shadow-primary/10 sm:p-8"><div className="absolute -right-16 -top-20 size-64 rounded-full border-[24px] border-primary-foreground/10" /><div className="relative flex flex-wrap items-start justify-between gap-6"><div><div className="flex items-center gap-2 text-primary-foreground/70"><Database className="size-5" /><span className="font-mono text-xs font-semibold uppercase tracking-widest">Developer workspace</span></div><h1 className="mt-3 text-3xl font-semibold tracking-tight">SQL Manager</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-primary-foreground/70">Explore tabelas, consulte registros e execute operações administrativas com segurança, rastreabilidade e contexto.</p></div><div className="flex items-center gap-2"><Badge variant="outline" className="gap-1.5 px-3 py-1.5"><ShieldCheck className="size-3.5" />Acesso administrativo</Badge><Button variant="outline" size="sm" onClick={loadTables}><RefreshCw className="size-4" data-icon="inline-start" />Atualizar</Button></div></div></header>
    <div className="grid min-h-[650px] flex-1 gap-5 xl:grid-cols-[260px_minmax(0,1fr)]">
      <Card className="overflow-hidden"><CardHeader className="border-b bg-muted/30 pb-4"><CardTitle className="flex items-center gap-2 text-sm"><Table2 className="size-4 text-primary" />Tabelas <Badge variant="secondary" className="ml-auto">{tables.length}</Badge></CardTitle><div className="relative mt-3"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Filtrar tabelas" value={filter} onChange={e => setFilter(e.target.value)} /></div></CardHeader><CardContent className="max-h-[570px] overflow-auto p-2"><div className="flex flex-col gap-1">{visible.map(t => <button key={t.table_name} onClick={() => openTable(t.table_name)} className={`flex items-center justify-between rounded-md px-3 py-2 text-left text-sm transition-colors hover:bg-accent ${selected === t.table_name ? "bg-primary/10 text-primary" : "text-foreground"}`}><span className="flex min-w-0 items-center gap-2"><Table2 className="size-3.5 shrink-0" /><span className="truncate font-mono">{t.table_name}</span></span><span className="text-xs text-muted-foreground">{t.row_count}</span></button>)}</div></CardContent></Card>
      <div className="flex min-w-0 flex-col gap-5"><Card><CardHeader className="border-b pb-3"><CardTitle className="flex items-center gap-2 text-sm"><Terminal className="size-4 text-primary" />Editor SQL <span className="ml-auto font-mono text-xs font-normal text-muted-foreground">PostgreSQL · sem ponto e vírgula</span></CardTitle></CardHeader><CardContent className="p-4"><Textarea value={sql} onChange={e => setSql(e.target.value)} className="min-h-32 resize-y bg-muted/30 font-mono text-sm leading-6" aria-label="Editor de comandos SQL" /><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Permitidos: SELECT, SHOW, DESCRIBE, EXPLAIN, INSERT, UPDATE e DELETE. SELECT exige LIMIT.</p><Button onClick={execute} disabled={busy || !sql.trim()}><Play className="size-4" data-icon="inline-start" />{busy ? "Executando..." : "Executar"}</Button></div></CardContent></Card>
        <Card className="min-h-0 flex-1 overflow-hidden"><CardHeader className="flex-row items-center border-b py-3"><CardTitle className="text-sm">{active ? `Resultado${selected ? ` · ${selected}` : ""}` : "Resultado da consulta"}</CardTitle>{active && <div className="ml-auto flex gap-2"><Button variant="outline" size="sm" onClick={() => download(csv(active), "sql-result.csv", "text/csv")}><Download className="size-4" data-icon="inline-start" />CSV</Button><Button variant="outline" size="sm" onClick={() => download(JSON.stringify(active.rows, null, 2), "sql-result.txt", "text/plain")}><Download className="size-4" data-icon="inline-start" />TXT</Button><Button variant="ghost" size="icon" onClick={() => { setResult(null); setDetail(null) }} aria-label="Limpar resultado"><X className="size-4" /></Button></div>}</CardHeader><CardContent className="overflow-auto p-0">{active ? <table className="w-full min-w-max text-left text-sm"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr>{active.columns.map(c => <th key={c} className="whitespace-nowrap px-4 py-3 font-mono font-medium">{c}</th>)}</tr></thead><tbody>{active.rows.map((row, i) => <tr key={i} className="border-t hover:bg-muted/30">{active.columns.map(c => <td key={c} className="max-w-64 whitespace-nowrap px-4 py-3 font-mono text-xs">{row[c] === null ? <span className="text-muted-foreground">NULL</span> : String(row[c])}</td>)}</tr>)}</tbody></table> : <div className="flex min-h-64 flex-col items-center justify-center gap-2 p-8 text-center text-muted-foreground"><Terminal className="size-8 opacity-40" /><p className="text-sm">Selecione uma tabela ou execute um comando SQL</p></div>}</CardContent>{active && <><Separator /><div className="px-4 py-2 text-xs text-muted-foreground">{active.rows.length} registro(s) exibido(s){result?.executionTime ? ` · ${result.executionTime} ms` : ""}</div></>}</Card></div>
    </div>
  </div>
}
